version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - ponfertato
    commit-message:
      prefix: "⬆️dep: "
      prefix-development: "⬆️dev dep: "
      include: "scope"
