export const expressionCharacter = {
  Sneeze: ["Sneeze", "Bersin", "Hachoo", "Atchoo", "Hatchi", "Achoo"],
  Sleep: ["Sleep", "Tidur", "Tertidur", "Ngantuk", "Pulas", "Lelah"],
  Yawn: ["Yawn", "Menguap", "Ngantuk", "Bosanan", "Menghela napas", "Kuap"],
  Love: ["Love", "Cinta", "Kasih", "Sayang", "Mencintai", "Menyukai", "Asmara", "Cinta kasih"],
  Laugh: ["Laugh", "Tertawa", "Tertawa keras", "Ketawa", "Ngakak", "Gerr", "Tawa lepas"],
  Giggle: ["Giggle", "Terkikik", "Tawa kecil", "Tawa geli", "Tertawa kecil", "Kekeh"],
  Annoyed: ["Annoyed", "Kesal", "Jengkel", "Sebal", "Marah", "Geram", "Kesel"],
  Nod: ["Nod", "Mengangguk", "Angguk", "Ngeangguk", "Anggukan", "Angguk kepala"],
  "Double nod": ["Double nod", "Mengangguk dua kali", "Angguk dua kali", "Angguk-angguk", "Nod dua kali", "Kepala dua kali"],
  "Head shake": ["Head shake", "Menggeleng", "Geleng", "Geleng kepala", "Menggelengkan kepala", "Geleng-geleng"],
  "Happy wink": ["Happy wink", "Kedip senang", "Kedipan senang", "Kedip bahagia", "Kedipan bahagia", "Wink senang"],
  "Cheeky wink": ["Cheeky wink", "Kedip nakal", "Kedipan nakal", "Kedip usil", "Kedipan usil", "Wink nakal"],
  "Silly wink": ["Silly wink", "Kedip konyol", "Kedipan konyol", "Kedip lucu", "Kedipan lucu", "Wink konyol"],
  Blush: ["Blush", "Merona", "Malu", "Pipinya merah", "Tersipu", "Tersipu-sipu"],
  "Disable blinking": ["Disable blinking", "Nonaktifkan kedipan", "Matikan kedipan", "Hentikan kedipan", "Tidak berkedip", "Stop kedip"],
  Blink: ["Blink", "Kedip", "Berkedip", "Kedipan", "Kedip mata", "Mengedip"],
  Cry: ["Cry", "Nangis", "Menangis", "Cengeng", "Ngambek", "Bersedih", "Tangisan", "Meratap"],
  Tears: ["Tears", "Air mata", "Sedih", "Meneteskan air mata", "Tangisan", "Isak", "Isakan"],
  Shocked: ["Shocked", "Terkejut", "Kaget", "Tercengang", "Terkaget", "Kaget sekali", "Terperangah"],
  Kiss: ["Kiss", "Cium", "Ciuman", "Mencium", "Pecah", "Kecupan", "Kecup"],
  "Sit down / Land": ["Sit down", "Land", "Duduk", "Mendarat", "Turun"],
  "Stand up / Fly up": ["Stand up", "Fly up", "Berdiri", "Terbang", "Naik"],
  Boop: ["Boop", "Sentuh", "Tekan", "Sentuhan", "Tepuk"],
  "Turn head": ["Turn head", "Putar kepala", "Gerakkan kepala", "Belokkan kepala", "nengok", "tengok kesamping", "nengok kesamping"],
  "Use item / Interact": ["Use item", "Interact", "Gunakan item", "Berinteraksi", "Pakai barang"],
  "Eat item": ["Eat item", "Makan barang", "Makan", "Konsumsi", "Memakan"],
  "Nom item": ["Nom item", "Kunyah barang", "Ngemil", "Makan kecil", "Cemil"],
  "Drop item": ["Drop item", "Jatuhkan barang", "Lepas barang", "Buang barang"],
  "Drop toy": ["Drop toy", "Jatuhkan mainan", "Lepas mainan", "Buang mainan"],
  "Drop dish": ["Drop dish", "Jatuhkan piring", "Lepas piring", "Buang piring"],
  "Select toy": ["Select toy", "Pilih mainan", "Ambil mainan"],
  Magic: ["Magic", "Sihir", "Mantra", "Ajaib"],
  "Pull mask down/up": ["Pull mask down", "Pull mask up", "Tarik masker turun", "Tarik masker naik"],
  "Edit character": ["Edit character", "Ubah karakter", "Sunting karakter"],
  "Zoom in": ["Zoom in", "Perbesar", "Dekatkan"],
  "Zoom out": ["Zoom out", "Perkecil", "Jauhkan"],
  "Center camera": ["Center camera", "Pusatkan kamera", "Tengah kamera"]
};
